export enum AntiNukeAction {
  BOT_ADD = "BOT_ADD",

  MASS_BAN = "MASS_BAN",
  MASS_KICK = "MASS_KICK",

  CHANNEL_CREATE = "CHANNEL_CREATE",
  CHANNEL_DELETE = "CHANNEL_DELETE",
  CHANNEL_UPDATE = "CHANNEL_UPDATE",

  ROLE_CREATE = "ROLE_CREATE",
  ROLE_DELETE = "ROLE_DELETE",
  ROLE_UPDATE = "ROLE_UPDATE",

  WEBHOOK_CREATE = "WEBHOOK_CREATE",

  SERVER_UPDATE = "SERVER_UPDATE",
}